Lab Production Review
konveyor/labs pull request #74
Opened 2023-09-05 18:18 UTC by hhpatel14

Doc: https://docs.google.com/document/d/1Vu5Bhsy7MOMbWjGHGYX2SvQkY0QqxAgM461pJaFSSew/edit#heading=h.hatt9vmiupfw

2023-09-05 18:45 UTC, kaovilai requested changes

2023-09-05 18:45 UTC, kaovilai commented on oadp/bookbag/workshop/content/exercises/Ex4.adoc
> +For a step by step understanding please reference our https://cloud.redhat.com/blog/an-overview-of-data-mover[public blog]. For this demonstration we will summarize the backup workflow.
```suggestion
For a step by step understanding please reference our https://cloud.redhat.com/blog/an-overview-of-data-mover[blog]. For this demonstration we will summarize the backup workflow.
```

2023-09-05 18:45 UTC, kaovilai commented on oadp/bookbag/workshop/content/exercises/Ex4.adoc
> +For a step by step understanding please reference our https://cloud.redhat.com/blog/an-overview-of-data-mover[public blog]. For this demonstration we will summarize the restore workflow.
```suggestion
For a step by step understanding please reference our https://cloud.redhat.com/blog/an-overview-of-data-mover[blog]. For this demonstration we will summarize the restore workflow.
```

2023-09-05 19:34 UTC, kaovilai approved these changes

2023-09-05 19:41 UTC, shubham-pampattiwar approved these changes

2023-09-06 14:11 UTC, sseago approved these changes

2023-09-06 20:03 UTC, weshayutin approved these changes

2023-09-06 20:04 UTC, merged